-- AlterEnum
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'FACTORY';

-- AlterEnum
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'PREPARED';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'LOAD_NOTIFIED';
